package com.iwinner.importer.website;

public class test {
	1mobile.com
    911cd.net
    9tut.com
    Pendriveapps.com
    PortableApps.com
    aade.com/XPhint/XPrecovery.htm
    adbdriver.com
    alternativeto.net
    androidcentral.com
    answersthatwork.com
    appbrain.com
    askvg.com
    cameyo.com
    cb.vu/unixtoolbox.xhtml
    cgiproxy.at
    clockworkmod.com/tether/drivers
    community.wdc.com/t5/WD-Portable-Drives/500GB-HDD-shows-465GB-internally/td-p/11697
    computerhope.com
    computernetworkingnotes.com
    convertfiles.com
    costtocost.in/list/pricelist.pdf
    cyberciti.biz
    datacent.com/hard_drive_sounds.php
    dedoimedo.com
    dedoimedo.com/computers/windows-wmic.html
    developer.android.com/tools/extras/oem-usb.html
    diddy.boot-land.net/grub4dos/files/boot.htm
    diddy.boot-land.net/grub4dos/files/menu.htm
    dreamincode.net
    droidextra.org/2013/02/06/install-adb-drivers-for-any-android-device.html
    en.kioskea.net
    express-files.com
    feedshark.brainbliss.com
    filehippo.com
    getjar.com
    goodells.net/multiboot
    goqr.me
    gpsearch.azurewebsites.net
    grammar.net
    hardwaresecrets.com
    hclsupportservice.in/metablet
    hddguru.com/software/HDD-LLF-Low-Level-Format-Tool
    hiren.info/pages/bootcd-on-usb-disk
    hirensbootcd.org/download
    ibm.com/developerworks/linux/library
    inetdaemon.com
    inetdaemon.com
    iso2usb.sourceforge.net
    it-ebooks.info
    ixconverter.net
    kellys-korner-xp.com/xp.htm
    kellys-korner-xp.com/xp_tweaks.htm
    lbis.kenyon.edu/helpline/printers/troubleshooting
    liberkey.com
    liberkey.com/en.html
    linuxcommand.org
    linuxhomenetworking.com
    livecdlist.com
    mabsoft.com/nettools.htm
    maximumpc.com
    mcmcse.com
    microsoft.com/windows/virtual-pc/download.aspx
    mobile9.com
    mossywell.com/boot-sequence
    msfn.org/board/topic/120444-how-to-install-windows-from-usb-winsetupfromusb-with-gui
    multibooters.co.uk/multiboot.html
    mydigitallife.info
    nehruplacemarket.com/price-list.html
    nick.rozanski.org.uk/index.php?page=multboot#stdboot
    nirsoft.net
    opendns.com
    pcguide.com
    pcruneasy.com/run-commands.php
    pendriveapps.com
    pendrivelinux.com
    pendrivelinux.com/universal-usb-installer-easy-as-1-2-3
    pendrivelinux.com/yumi-multiboot-usb-creator
    plop.at/en/bootmanagers.html
    portableapps.com
    portablefreeware.com
    qrstuff.com
    qru.nu
    ratetorate.in
    reboot.pro/files
    rmprepusb.com
    routeralley.com/ra/index.html
    screenshots.leeindy.com
    sitemapx.com/index.html
    ss64.com
    ss64.com/nt/run.html
    startapp.com
    supergrubdisk.org
    technet.microsoft.com/en-us/sysinternals
    theunlockr.com
    tomshardware.com
    vbox.me
    virtualboxes.org/images
    vkernel.ro/blog
    wiki.centos.org/TipsAndTricks/MultimediaOnCentOS
    winhelp.us
    winpenpack.com
    wintoflash.com/download/en
    www-uxsup.csx.cam.ac.uk/pub/doc/suse/suse9.0/adminguide-9.0/node8.html
    www.justbeamit.com
    xda-developers.com
    zbigz.com

}
